### ISSUE TITLE
Documentation available for AMD Zen and Zen 2

### ISSUE THREAD

**Issue by travisdowns** [andreas-abel/nanoBench#11]
In case you wanted to fill out the documentation category for AMD chips, it seems that AMD has made available the latency spreadsheet for [Zen](https://developer.amd.com/wordpress/media/2013/12/55723_3_00.ZIP) and [Zen 2 (?)](https://www.amd.com/system/files/TechDocs/56305.zip).

**Comment by andreas-abel** [comment]
Thanks. I was aware of the spreadsheet for Zen (which is also linked on https://developer.amd.com/resources/developer-guides-manuals/) but I hadn't seen the new one for Zen 2 yet. The main reason why I haven't added the data to the website yet is that it is not straight-forward to match the entries in the spreadsheet with the corresponding instruction variants automatically (and the table is too large to do it manually).

**Comment by andreas-abel** [comment]
Data from the documentation is now available on uops.info.
