### ISSUE TITLE
replPolicy.py default -sets value doesn't work

### ISSUE THREAD

**Issue by caizixian** [andreas-abel/nanoBench#21]
https://github.com/andreas-abel/nanoBench/blob/4e7954f/tools/CacheAnalyzer/replPolicy.py#L61

The code suggests that if I leave `-sets` empty, all sets will be tested.
However, running that will result in this error 

https://github.com/andreas-abel/nanoBench/blob/d70535f/tools/CacheAnalyzer/cacheSim.py#L309

**Comment by andreas-abel** [comment]
I guess this was copy-and-paste from cacheSeq.py. I changed it.
