### ISSUE TITLE
Read MSR_PKG_ENERGY_STATUS fails

### ISSUE THREAD

**Issue by kaposnick** [andreas-abel/nanoBench#31]
Hi, I am trying to read the MSR_PKG_ENERGY_STATUS using the user-mode nanobenchmark (as declared in configs/msr_RAPL.txt). 

However, it fails with error: 
'invalid configuration: msr_611'. 

I inspected the code and I suspect that it comes from the following line: https://github.com/andreas-abel/nanoBench/blob/faf75236cade57f7927f9ee949ebc679fc7864b7/common/nanoBench.c#L199

where it doesn't find any '.' in the configuration line. 

Has been made any architectural decision to only support the MSR_3F6H, MSR_PF, MSR_RSP0, MSR_RSP1 in the userspace? Is MSR_PKG_ENERGY_STATUS supported in the kernel space?

Thanks a lot!

**Comment by andreas-abel** [comment]
The msr_* config files have to be used with the `-msr_config` option, which is only available in the kernel version.
