### ISSUE TITLE
Missing latency entry for gathers

### ISSUE THREAD

**Issue by travisdowns** [andreas-abel/nanoBench#5]
You measure many [latency stats for gathers](http://uops.info/html-lat/SKL/VPGATHERDD_YMM_VSIB_YMM_YMM-Measurements.html#lat2-%3E1_addr) which is awesome (and a very important formalization of the way we think about latency), but I think you are missing the most important one.

That is is the 2 -> 1 (address) latency but through the vector index register, not the base register. That's probably the most common latency chain you'll have in practice because it generalizes the notion of pointer chasing. That is, a loop like:

```
vpgatherdd ymm0,DWORD PTR [r14+ymm14*1],ymm1
vpor ymm14,ymm0,ymm0
```

On my SKL machine I measure the same latency (22) for this: same as for the 3->1 latency.

**Comment by andreas-abel** [comment]
Fixed.

**Comment by travisdowns** [comment]
Thanks @andreas-abel!
